name: CI
on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'src'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - 'src'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Rust
      run: |
        rustup set profile minimal
        rustup toolchain install stable
        rustup default stable
    - name: Install mdbook and plugins
      uses: actions-rs/cargo@v1
      with:
        command: install
        args: mdbook mdbook-toc
    - name: Run tests
      run: mdbook test
